### ISSUE TITLE
Kitgive and can’t put Items with : in their id

### ISSUE THREAD

**Issue by Hzste** [AlexPads/KitsPlus#12]
Kitgive just says internal server error. And I can’t add items in kits that have a : on their is as it goes towards damage

**Comment by AlexPads** [comment]
@BloodFistMCPE Can I please have the error that it throws in console? or in logs? Thanks!

**Comment by Hzste** [comment]
> @BloodFistMCPE Can I please have the error that it throws in console? or in logs? Thanks!

12.11 15:40:01 [Server] Server thread/INFO BloodFistV3> /kitgive
12.11 15:40:01 [Server] Server thread/CRITICAL ErrorException: "Undefined offset: 0" (EXCEPTION) in "plugins/KitsPlus-master/src/SaltyPixelDevz/ChestKits/Main" at line 284
12.11 15:40:01 [Server] Server thread/DEBUG #0 plugins/KitsPlus-master/src/SaltyPixelDevz/ChestKits/Main(284): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[19] Undefined offset: 0, string[108] /plugins/KitsPlus-master/src/Salty, integer 284, array[3])
12.11 15:40:01 [Server] Server thread/DEBUG #1 plugins/KitsPlus-master/src/SaltyPixelDevz/ChestKits/Main(62): SaltyPixelDevz\ChestKits\Main->typeList(object pocketmine\Player, array[0])
12.11 15:40:01 [Server] Server thread/DEBUG #2 src/pocketmine/command/PluginCommand(58): SaltyPixelDevz\ChestKits\Main->onCommand(object pocketmine\Player, object pocketmine\command\PluginCommand, string[7] kitgive, array[0])
12.11 15:40:01 [Server] Server thread/DEBUG #3 src/pocketmine/command/SimpleCommandMap(270): pocketmine\command\PluginCommand->execute(object pocketmine\Player, string[7] kitgive, array[0])
12.11 15:40:01 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2035): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[7] kitgive)
12.11 15:40:01 [Server] Server thread/DEBUG #5 src/pocketmine/Player(2312): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[7] kitgive)
12.11 15:40:01 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[8] /kitgive)
12.11 15:40:01 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
12.11 15:40:01 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
12.11 15:40:01 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
12.11 15:40:01 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
12.11 15:40:01 [Server] Server thread/DEBUG #11 src/pocketmine/Player(3205): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
12.11 15:40:01 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
12.11 15:40:01 [Server] Server thread/DEBUG #13 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 94.194.213.187 59226, object raklib\protocol\EncapsulatedPacket, integer 0)
12.11 15:40:01 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
12.11 15:40:01 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
12.11 15:40:01 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
12.11 15:40:01 [Server] Server thread/DEBUG #17 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
12.11 15:40:01 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2355): pocketmine\snooze\SleeperHandler->sleepUntil(double 1573573201.4619)
12.11 15:40:01 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2212): pocketmine\Server->tickProcessor()
12.11 15:40:01 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1790): pocketmine\Server->start()
12.11 15:40:01 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
12.11 15:40:01 [Server] Server thread/DEBUG #22 src/pocketmine/PocketMine(299): pocketmine\server()
12.11 15:40:01 [Server] Server thread/DEBUG #23 (1): require(string[95] phar:///custom.phar/src/pocketmine)
12.11 15:40:01 [Server] Server thread/INFO ➼[-] BloodFistV3 has left the game!
12.11 15:40:01 [Server] Server thread/INFO BloodFistV3[/94.194.213.187:59226] logged out due to Internal server error
12.11 15:40:01 [Server] RakLibServer thread/NOTICE Blocked 94.194.213.187 for 5 seconds
