### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by jaylac2000** [AlexPads/KitsPlus#14]
/kitgive Kit Player

=

 [Server thread/CRITICAL]: TypeError: "Argument 1 passed to WitherHosting\ChestKits\Main::typeList() must be an instance of pocketmine\Player, null given, called in C:\Users\Administrator\Documents\mc servers\TestSERVERS\devtools\plugins\KitPlus\src\WitherHosting\ChestKits\Main.php on line 83" (EXCEPTION) in "plugins/KitPlus/src/WitherHosting/ChestKits/Main" at line 287

**Comment by jaylac2000** [comment]
[Server thread/CRITICAL]: Error: "Call to a member function getSize() on array" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 158

**Comment by AlexPads** [comment]
Thanks will look into this soon. The plugin was working in all of my tests before the update.

**Comment by AlexPads** [comment]
Please run the command in-game. I will add a check for this soon.
