### ISSUE TITLE
umm...........

### ISSUE THREAD

**Issue by creeperplayer20** [AlexPads/KitsPlus#15]
when i open the chest and when i click on the boots it shows Guest "Helmet"

    Boots: "313:0:1:§r§7Guest Boots:0,17:2,2"
![Minecraft 04 02 2020 22_10_42](https://user-images.githubusercontent.com/42560781/73787285-43219a00-479b-11ea-9faa-1e05f60052b6.png)

**Comment by AlexPads** [comment]
Can I see your whole config file?
