### ISSUE TITLE
Kits not working!

### ISSUE THREAD

**Issue by ghost** [AlexPads/KitsPlus#2]
Hey alex what am i doing wrong here?!? ❓, it crashes when i claim a kit, i think its something to do with custom item/gear names

Kits:
  Starter:
    Cost: 0
    Permission: "kit.starter"
    KitFormName: "Starter"
    KitChestName: "§7§lStarter§r§7 Kit"
    Helmet: "310:0:1:§7§lStarter§r§7 Helmet:0,5:2,1"
    Chestplate: "311:0:1:§7§lStarter§r§7 Chestplate:0:2"
    Leggings: "312:0:1:§7§lStarter§r§7 Leggings:0:2"
    Boots: "313:0:1:§7§lStarter§r§7 Boots:0:2"
    CooldownTime: 25
    Items:
      - "276:0:1:§7§lStarter§r§7 Sword:9:2"
      - "279:0:1:§7§lStarter§r§7 Axe:9,15:2,2"
      - "278:0:1:§7§lStarter§r§7 Pickaxe:15:2"
      - "steak:0:64" 
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Weekly:
    Cost: 0
    Permission: "kit.weekly"
    KitFormName: "Weekly"
    KitChestName: "§a§lWeekly§r§7 Kit"
    Helmet: "310:0:1:§a§lWeekly§r§7 Helmet:0,5:2,1"
    Chestplate: "311:0:1:§a§lWeekly§r§7 Chestplate:0:2"
    Leggings: "312:0:1:§a§lWeekly§r§7 Leggings:0:2"
    Boots: "313:0:1:§a§lWeekly§r§7 Boots:0,Gears:2,4"
    CooldownTime: 25
    Items:
      - "276:0:1:§a§lWeekly§r§7 Sword:9:2"
      - "279:0:1:§a§lWeekly§r§7 Axe:9,15:2,2"
      - "278:0:1:§a§lWeekly§r§7 Pickaxe:15:2"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Monthly:
    Cost: 0
    Permission: "kit.monthly"
    KitFormName: "Monthly"
    KitChestName: "§c§lMonthly§r§7 Kit"
    Helmet: "310:0:1:§c§lMonthly§r§7 Helmet:0,5:3,1"
    Chestplate: "311:0:1:§c§lMonthly§r§7 Chestplate:0:3"
    Leggings: "312:0:1:§c§lMonthly§r§7 Leggings:0:3"
    Boots: "313:0:1:§c§lMonthly§r§7 Boots:0,Gears:3,4"
    CooldownTime: 25
    Items:
      - "276:0:1:§c§lMonthly§r§7 Sword:9:3"
      - "279:0:1:§c§lMonthly§r§7 Axe:9,15:3,3"
      - "278:0:1:§c§lMonthly§r§7 Pickaxe:15:3"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Mage:
    Cost: 0
    Permission: "kit.mage"
    KitFormName: "Mage"
    KitChestName: "§e§lMage§r§7 Kit"
    Helmet: "310:0:1:§e§lMage§r§7 Helmet:0,5:3,2"
    Chestplate: "311:0:1:§e§lMage§r§7 Chestplate:0:4"
    Leggings: "312:0:1:§e§lMage§r§7 Leggings:0:4"
    Boots: "313:0:1:§e§lMage§r§7 Boots:0,Gears:4,4"
    CooldownTime: 25
    Items:
      - "276:0:1:§e§lMage§r§7 Sword:9,17:3,1"
      - "279:0:1:§e§lMage§r§7 Axe:9,15,17:3,3,1"
      - "278:0:1:§e§lMage§r§7 Pickaxe:15,17:3,1"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  King:
    Cost: 0
    Permission: "kit.king"
    KitFormName: "King"
    KitChestName: "§b§lKing§r§7 Kit"
    Helmet: "310:0:1:§b§lKing§r§7 Helmet:0,5,17:3,2,4"
    Chestplate: "311:0:1:§b§lKing§r§7 Chestplate:0:5"
    Leggings: "312:0:1:§b§lKing§r§7 Leggings:0,17:5,4"
    Boots: "313:0:1:§b§lKing§r§7 Boots:0,Gears,17:5,4,4"
    CooldownTime: 25
    Items:
      - "276:0:1:§b§lKing§r§7 Sword:9,17:3,1"
      - "279:0:1:§b§lKing§r§7 Axe:9,15,17:5,4,3"
      - "278:0:1:§b§lKing§r§7 Pickaxe:15,17:4,3"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Elite:
    Cost: 0
    Permission: "kit.elite"
    KitFormName: "Elite"
    KitChestName: "§2§lElite§r§7 Kit"
    Helmet: "310:0:1:§2§lElite§r§7 Helmet:0,5,17:6,3,5"
    Chestplate: "311:0:1:§2§lElite§r§7 Chestplate:0:6"
    Leggings: "312:0:1:§2§lElite§r§7 Leggings:0,17:6,5"
    Boots: "313:0:1:§2§lElite§r§7 Boots:0,Gears,17:6,4,5"
    CooldownTime: 25
    Items:
      - "276:0:1:§2§lElite§r§7 Sword:9,17:5,3"
      - "279:0:1:§2§lElite§r§7 Axe:9,15,17:5,4,4"
      - "278:0:1:§2§lElite§r§7 Pickaxe:15,17:5,4"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Assassin:
    Cost: 0
    Permission: "kit.assassin"
    KitFormName: "Assassin"
    KitChestName: "§e§lAssassin§r§7 Kit"
    Helmet: "310:0:1:§e§lAssassin§r§7 Helmet:0,5,17:7,5,6"
    Chestplate: "311:0:1:§e§lAssassin§r§7 Chestplate:0:7"
    Leggings: "312:0:1:§e§lAssassin§r§7 Leggings:0,17:7,6"
    Boots: "313:0:1:§e§lAssassin§r§7 Boots:0,Gears,17:7,5,6"
    CooldownTime: 25
    Items:
      - "276:0:1:§e§lAssassin§r§7 Sword:9,17:6,4"
      - "279:0:1:§e§lAssassin§r§7 Axe:9,15,17:6,5,5"
      - "278:0:1:§e§lAssassin§r§7 Pickaxe:15,17:6,5"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Ultimate:
    Cost: 0
    Permission: "kit.ultimate"
    KitFormName: "Ultimate"
    KitChestName: "§5§lUltimate§r§7 Kit"
    Helmet: "310:0:1:§5§lUltimate§r§7 Helmet:0,5,17:8,5,7"
    Chestplate: "311:0:1:§5§lUltimate§r§7 Chestplate:0:8"
    Leggings: "312:0:1:§5§lUltimate§r§7 Leggings:0,17:8,7"
    Boots: "313:0:1:§5§lUltimate§r§7 Boots:0,Gears,17:8,5,7"
    CooldownTime: 25
    Items:
      - "276:0:1:§5§lUltimate§r§7 Sword:9,17:7,6"
      - "279:0:1:§5§lUltimate§r§7 Axe:9,15,17:7,6,6"
      - "278:0:1:§5§lUltimate§r§7 Pickaxe:15,17:7,6"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Warlord:
    Cost: 0
    Permission: "kit.warlord"
    KitFormName: "Warlord"
    KitChestName: "§c§lWarlord§r§7 Kit"
    Helmet: "310:0:1:§c§lWarlord§r§7 Helmet:0,5,17:9,5,8"
    Chestplate: "311:0:1:§c§lWarlord§r§7 Chestplate:0,17:9,8"
    Leggings: "312:0:1:§c§lWarlord§r§7 Leggings:0,17:9,8"
    Boots: "313:0:1:§c§lWarlord§r§7 Boots:0,Gears,17:9,5,8"
    CooldownTime: 25
    Items:
      - "276:0:1:§c§lWarlord§r§7 Sword:9,17:8,7"
      - "279:0:1:§c§lWarlord§r§7 Axe:9,15,17:8,7,7"
      - "278:0:1:§c§lWarlord§r§7 Pickaxe:15,17:8,7"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Demigod:
    Cost: 0
    Permission: "kit.demigod"
    KitFormName: "Demigod"
    KitChestName: "§a§lDemiGod§r§7 Kit"
    Helmet: "310:0:1:§a§lDemiGod§r§7 Helmet:0,5,17:10,5,9"
    Chestplate: "311:0:1:§a§lDemiGod§r§7 Chestplate:0,17:10,9"
    Leggings: "312:0:1:§a§lDemiGod§r§7 Leggings:0,17:10,9"
    Boots: "313:0:1:§a§lDemiGod§r§7 Boots:0,Gears,17:10,5,9"
    CooldownTime: 25
    Items:
      - "276:0:1:§a§lDemiGod§r§7 Sword:9,17:9,8"
      - "279:0:1:§a§lDemiGod§r§7 Axe:9,15,17:9,8,8"
      - "278:0:1:§a§lDemiGod§r§7 Pickaxe:15,17:9,8"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"
  Overlord:
    Cost: 0
    Permission: "kit.overlord"
    KitFormName: "Overlord"
    KitChestName: "§0§lOverlord§r§7 Kit"
    Helmet: "310:0:1:§0§lOverlord§r§7 Helmet:0,5,17:12,5,12"
    Chestplate: "311:0:1:§0§lOverlord§r§7 Chestplate:0,17:12,12"
    Leggings: "312:0:1:§0§lOverlord§r§7 Leggings:0,17:12,12"
    Boots: "313:0:1:§0§lOverlord§r§7 Boots:0,Gears,17:12,5,12"
    CooldownTime: 25
    Items:
      - "276:0:1:§0§lOverlord§r§7 Sword:9,17:12,12"
      - "279:0:1:§0§lOverlord§r§7 Axe:9,15,17:12,12,12"
      - "278:0:1:§0§lOverlord§r§7 Pickaxe:15,17:12,12"
      - "steak:0:64"
      - "17:0:64"
      - "7:0:16" 
      - "obsidian:0:32"`

**Comment by AlexPads** [comment]
Ok we fixed this on discord already.
