### ISSUE TITLE
error on /kitgive

### ISSUE THREAD

**Issue by ghost** [AlexPads/KitsPlus#9]
I tried to do /kitgive and...
 ErrorException: "Undefined offset: 0" (EXCEPTION) in "plugins/KitsPlus (1).phar/src/SaltyPixelDevz/ChestKits/Main" at line 284. I just did /kitgive. I tried doing /kitgive Starter Play2Kill and 
 TypeError: "Argument 1 passed to SaltyPixelDevz\ChestKits\Main::typeList() must be an instance of pocketmine\Player, null given, called in phar:///home/minecraft/plugins/KitsPlus (1).phar/src/SaltyPixelDevz/ChestKits/Main.php on line 82" (EXCEPTION) in "plugins/KitsPlus (1).phar/src/SaltyPixelDevz/ChestKits/Main" at line 281

**Comment by ghost** [comment]
Maybe i can just reedit the second error to tell if the person is online or not. Still not sure.

**Comment by AlexPads** [comment]
I'll fix this when I get home later today thanks for the report!

**Comment by ghost** [comment]
AlexPads is the cooldown time of the kits are on hours or minutes?

**Comment by AlexPads** [comment]
@Play2KillTV They are in Seconds actually.
